(function(){(window.webpackJsonp=window.webpackJsonp||[]).push([[2],{234:function(ke,db,e){e.r(db);var y=e(0);e.n(y);var x=e(21),r=e(8),h=e(4),b=e(55);db["default"]=function(a){function e(a){var b=[];for(a.wa();a.advance();){var e=a.Da();"field"===e?b.push(String(a.V("name"))):console.warn("unrecognised field list element: "+e)}a.Na();return b}function db(a,b){return b?"false"===a?!1:!0:"true"===a?!0:!1}function id(a,b){var f=a.Da();switch(f){case "javascript":return{name:"JavaScript",javascript:a.current.textContent};
case "uri":return{name:"URI",uri:a.V("uri")};case "goto":f=null;a.wa();if(a.advance()){var h=a.V("fit");f={page:a.V("page"),fit:h};if("0"===f.page)console.warn("null page encountered in dest");else switch(b=b(Number(f.page)),h){case "Fit":case "FitB":break;case "FitH":case "FitBH":f.top=b.ha({x:0,y:a.V("top")||0}).y;break;case "FitV":case "FitBV":f.left=b.ha({x:a.V("left")||0,y:0}).x;break;case "FitR":h=b.ha({x:a.V("left")||0,y:a.V("top")||0});b=b.ha({x:a.V("right")||0,y:a.V("bottom")||0});b=new r.a(h.x,
h.y,b.x,b.y);f.top=b.aa;f.left=b.ea;f.bottom=b.ba;f.right=b.fa;break;case "XYZ":h=b.ha({x:a.V("left")||0,y:a.V("top")||0});f.top=h.y;f.left=h.x;f.zoom=a.V("zoom")||0;break;default:console.warn("unknown dest fit: "+h)}f={name:"GoTo",dest:f}}else console.bZ("missing dest in GoTo action");a.Na();return f;case "submit-form":f={name:"SubmitForm",url:a.V("url"),format:a.V("format"),method:a.V("method")||"POST",exclude:db(a.V("exclude"),!1)};b=a.V("flags");f.flags=b?b.split(" "):[];for(a.wa();a.advance();)switch(b=
a.Da(),b){case "fields":f.fields=e(a);break;default:console.warn("unrecognised submit-form child: "+b)}a.Na();return f;case "reset-form":f={name:"ResetForm",exclude:db(a.V("exclude"),!1)};for(a.wa();a.advance();)switch(b=a.Da(),b){case "fields":f.fields=e(a);break;default:console.warn("unrecognised reset-form child: "+b)}a.Na();return f;case "hide":f={name:"Hide",hide:db(a.V("hide"),!0)};for(a.wa();a.advance();)switch(b=a.Da(),b){case "fields":f.fields=e(a);break;default:console.warn("unrecognised hide child: "+
b)}a.Na();return f;case "named":return{name:"Named",action:a.V("name")};default:console.warn("Encountered unexpected action type: "+f)}return null}function w(a,b,e){var f={};for(a.wa();a.advance();){var h=a.Da();switch(h){case "action":h=a.V("trigger");if(b?-1!==b.indexOf(h):1){f[h]=[];for(a.wa();a.advance();){var n=id(a,e);Object(y.isNull)(n)||f[h].push(n)}a.Na()}else console.warn("encountered unexpected trigger on field: "+h);break;default:console.warn("encountered unknown action child: "+h)}}a.Na();
return f}function z(a){return"calculation-order"===a.Da()?e(a):[]}function n(a){return new h.a(a.V("r")||0,a.V("g")||0,a.V("b")||0,a.V("a")||1)}function ke(a,b){var e=a.V("name"),f=a.V("type")||"Type1",h=a.V("size"),r=b.ha({x:0,y:0});h=b.ha({x:Number(h),y:0});b=r.x-h.x;r=r.y-h.y;e={name:e,type:f,size:Math.sqrt(b*b+r*r)||0,strokeColor:[0,0,0],fillColor:[0,0,0]};for(a.wa();a.advance();)switch(f=a.Da(),f){case "stroke-color":e.strokeColor=n(a);break;case "fill-color":e.fillColor=n(a);break;default:console.warn("unrecognised font child: "+
f)}a.Na();return e}function oe(a,b){var e={border:{style:"Solid",width:1},backgroundColor:[],fieldName:a.V("field"),page:a.V("page"),index:a.V("index")||0,rotation:a.V("rotation")||0,flags:[]},f=a.V("appearance");f&&(e.appearance=f);(f=a.V("flags"))&&(e.flags=f.split(" "));for(a.wa();a.advance();)switch(f=a.Da(),f){case "rect":var h=a,x=b(Number(e.page));f=x.ha({x:h.V("x1")||0,y:h.V("y1")||0});h=x.ha({x:h.V("x2")||0,y:h.V("y2")||0});f=new r.a(f.x,f.y,h.x,h.y);f.normalize();e.rect={x1:f.x1,y1:f.y1,
x2:f.x2,y2:f.y2};break;case "border":f=a;h={style:f.V("style")||"Solid",width:f.V("width")||1,color:[0,0,0]};for(f.wa();f.advance();)switch(x=f.Da(),x){case "color":h.color=n(f);break;default:console.warn("unrecognised border child: "+x)}f.Na();e.border=h;break;case "background-color":e.backgroundColor=n(a);break;case "actions":e.actions=w(a,"E X D U Fo Bl PO PC PV PI".split(" "),b);break;case "appearances":f=a;h=pe.Bi(e,"appearances");for(f.wa();f.advance();)if(x=f.Da(),"appearance"===x){x=f.V("name");
var y=pe.Bi(h,x);x=f;for(x.wa();x.advance();){var z=x.Da();switch(z){case "Normal":pe.Bi(y,"Normal").data=x.current.textContent;break;default:console.warn("unexpected appearance state: ",z)}}x.Na()}else console.warn("unexpected appearances child: "+x);f.Na();break;case "extra":f=a;h=b;x={};for(f.wa();f.advance();)switch(y=f.Da(),y){case "font":x.font=ke(f,h(1));break;default:console.warn("unrecognised extra child: "+y)}f.Na();f=x;f.font&&(e.font=f.font);break;case "captions":h=a;f={};(x=h.V("Normal"))&&
(f.Normal=x);(x=h.V("Rollover"))&&(f.Rollover=x);(h=h.V("Down"))&&(f.Down=h);e.captions=f;break;default:console.warn("unrecognised widget child: "+f)}a.Na();return e}function le(a){var b={value:a.V("value")};(a=a.V("display-value"))&&(b.displayValue=a);return b}function we(b,e){var f=b.V("name"),h={type:b.V("type"),quadding:b.V("quadding")||"Left-justified",maxLen:b.V("max-len")||-1},n=b.V("flags");Object(y.isString)(n)&&(h.flags=n.split(" "));for(b.wa();b.advance();)switch(n=b.Da(),n){case "actions":h.actions=
w(b,["C","F","K","V"],e);break;case "default-value":n=b;n.wa();n.advance();var r=n.current.textContent;n.Na();h.defaultValue=r;break;case "font":h.font=ke(b,e);break;case "options":n=b;r=[];for(n.wa();n.advance();){var x=n.Da();switch(x){case "option":r.push(le(n));break;default:console.warn("unrecognised options child: "+x)}}n.Na();h.options=r;break;default:console.warn("unknown field child: "+n)}b.Na();return new a.Annotations.ga.oa(f,h)}function ue(a,b){switch(a.type){case "Tx":return new x.h(a,
b);case "Ch":return a.flags.get("Combo")?new x.c(a,b):new x.d(a,b);case "Btn":return a.flags.get("PushButton")?new x.e(a,b):a.flags.get("Radio")?new x.f(a,b):new x.b(a,b);case "Sig":return new x.g(a,b);default:console.warn("Unrecognised field type: "+a.type)}return null}function ve(a,b){var e={number:a.V("number")};for(a.wa();a.advance();){var f=a.Da();switch(f){case "actions":e.actions=w(a,["O","C"],b);break;default:console.warn("unrecognised page child: "+f)}}a.Na();return e}a.vf=a.vf||{};var pe=
a.vf;pe.$M={parse:function(a,e,f,h){var n=[],r={};a.wa();var x=[],y={},db=[];Object(b.a)(function(){if(a.advance()){var b=a.Da();switch(b){case "calculation-order":x=z(a);break;case "document-actions":y=w(a,["Init","Open"],e);break;case "pages":b=[];for(a.wa();a.advance();){var f=a.Da();switch(f){case "page":b.push(ve(a,e));break;default:console.warn("unrecognised page child: "+f)}}a.Na();db=b;break;case "field":b=we(a,e(1));r[b.name]=b;break;case "widget":f=oe(a,e);(b=r[f.fieldName])?(b=ue(b,f),
n.push(b)):console.warn("ignoring widget with no corresponding field data: "+f.fieldName);break;default:console.warn("Unknown element encountered in PDFInfo: "+b)}return!0}return!1},function(){a.Na();f({calculationOrder:x,widgets:n,fields:r,documentActions:y,pages:db,custom:[]})},h)},vV:we,zV:oe,tV:z}}(window)}}]);}).call(this || window)
